# Generated by cucumber-sinatra. (2011-05-05 13:43:58 -0400)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'fortune.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Fortune

class FortuneWorld
  include Capybara
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  FortuneWorld.new
end
